apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: k8s-multi-com-tls
spec:
  secreteName: letsencrypt-prod-key
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: offerpromogt.com
  dnsNames:
    - offerpromogt.com
    - www.offerpromogt.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - offerpromogt.com
          - www.offerpromogt.com